spring:
  profiles:
    active: pro
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: asd123@1
    url: jdbc:mysql://localhost:3306/jdbc?serverTimezone=UTC

mybatis:
  mapper-locations: classpath:cn/hors/mapper/sqlmap/*.xml
  type-aliases-package: cn.hors.bean
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    cn.hors: trace