server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hors
    password: 123456
    url: jdbc:mysql://localhost:3306/hors?serverTimezone=UTC

mybatis:
  mapper-locations: classpath:cn/hors/mapper/sqlmap/*.xml
  configuration:
    map-underscore-to-camel-case: true